name: CloudFlare DNS
description: |
  Rancher External DNS service powered by CloudFlare
<<<<<<< HEAD
version: v0.4.0-rancher1
category: Rancher Services
=======
version: v0.6.0-rancher1
category: External DNS
>>>>>>> upstream/master
