name: DNSimple DNS
description: |
  Rancher External DNS service powered by DNSimple
<<<<<<< HEAD
version: v0.2.1-rancher1
category: Rancher Services
=======
version: v0.6.0-rancher1
category: External DNS
>>>>>>> upstream/master
