name: DNS Update (RFC2136)
description: |
  Rancher External DNS service powered by any RFC2136 compatible DNS
<<<<<<< HEAD
version: v0.5.0-rancher1
category: Rancher Services
=======
version: v0.6.0-rancher1
category: External DNS
>>>>>>> upstream/master
