name: px-dev
description: |
  Software defined enterprise storage for Linux Containers.
<<<<<<< HEAD
version: 1.2.11.1-5ed364c
=======
version: 1.2.11.1-5ed364c
>>>>>>> upstream/master
category: Storage
