name: px-dev
description: |
  Software defined enterprise storage for Linux Containers.
<<<<<<< HEAD
version: 1.0.6-2016-10-05-GA
=======
version: 1.1.6-2017-02-08-GA
>>>>>>> upstream/master
category: Storage
