name: Bind9 Domain Name Server
description: |
  Bind9 DNS server, compatible with the "DNS Update (RFC2136)"
version: v1.0.0-rancher1
<<<<<<< HEAD
category: Rancher Services
=======
category: External DNS
>>>>>>> upstream/master
