name: Apache Zookeeper
description: |
  (Experimental) Zookeeper cluster
<<<<<<< HEAD
version: 3.4.8-rancher1
category: Clustering
maintainer: "Raul Sanchez <rawmind@gmail.com>"
minimum_rancher_version: v0.59.0
=======
version: 3.4.9-rancher1
category: Clustering
maintainer: "Raul Sanchez <rawmind@gmail.com>"
projectURL: https://github.com/rawmind0/alpine-zk
>>>>>>> upstream/master
license: 
