name: PointHQ DNS
description: |
  Rancher External DNS service powered by PointHQ
version: v0.2.1-rancher1
<<<<<<< HEAD
category: Rancher Services
=======
category: External DNS
>>>>>>> upstream/master
