secrets-bridge:
<<<<<<< HEAD
    image: rancher/secrets-bridge:v0.1.7
=======
    image: rancher/secrets-bridge:v0.1.8
>>>>>>> upstream/master
    command: agent --bridge-url ${BRIDGE_URL}
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    labels:
        io.rancher.container.create_agent: true
        io.rancher.container.agent.role: agent
        io.rancher.scheduler.global: true
