name: Minecraft
<<<<<<< HEAD
description: |
  Multiplayer block game for wasting lots of time
version: v1.8
=======
description: Multiplayer block game for wasting lots of time
version: v1.11
>>>>>>> upstream/master
category: Entertainment
maintainer: Steve Shipway <s.shipway@auckland.ac.nz>
