name: Etcd
description: |
  A distributed key/value store that provides a reliable way to store data across a cluster of machines
<<<<<<< HEAD
version: 2.3.7
=======
version: 2.3.7-beta.2
>>>>>>> upstream/master
category: Clustering
