<<<<<<< HEAD
name: Sysdig Cloud
description: |
  Container-Native Application and Infrastructure Monitoring
version: v0
category: Monitoring
=======
name: Sysdig Cloud v1
description: |
  Container-Native Application and Infrastructure Monitoring
version: v1
category: Rancher Services
>>>>>>> upstream/master
