name: Datadog
description: |
  Real-time performance tracking and visualization of your container-based application deployment
<<<<<<< HEAD
version: 11.3.585-rancher1
=======
version: 1.1.0-11.0.5110
>>>>>>> upstream/master
category: Monitoring
maintainer: "Jan Bruder <jan@rancher.com>"
license: The MIT License
