name: Apache Kafka
description: |
  (Experimental) Kafka cluster
<<<<<<< HEAD
version: 0.10.0.0-rancher1
=======
version: 0.10.0.1-rancher1
>>>>>>> upstream/master
category: Clustering
maintainer: "Raul Sanchez <rawmind@gmail.com>"
minimum_rancher_version: v0.59.0
license: 
<<<<<<< HEAD
=======
projectURL: https://github.com/rawmind0/alpine-kafka
>>>>>>> upstream/master
