name: PowerDNS External
description: |
  Rancher External DNS service for PowerDNS
version: v0.5.0-rancher1
<<<<<<< HEAD
category: Rancher Services
=======
category: External DNS
>>>>>>> upstream/master
