name: "Secrets Bridge Agents"
description: "Agent side of bridge between Vault and Rancher"
<<<<<<< HEAD
version: "0.0.1-rancher1"
=======
version: "0.1.0-rancher1"
>>>>>>> upstream/master
category: Security
